name: read-file

on:
  workflow_dispatch:

jobs:
  read-file-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout other repository
      uses: actions/checkout@v2

    - name: Read file
      run: |
         git clone --depth=1 https://github.com/virtual-labs/cfg-vlabs-infra
         cd cfg-vlabs-infra
         ls -R
