name: read-file-

on:
  workflow_dispatch:

jobs:
  read-file-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: vikramk20/cfg-vlabs-infra
        token: ${{ secrets.GITHUB_TOKEN }} # Replace with the access token with appropriate permissions
        ref: main # Replace with the branch or commit from which you want to access the file

    - name: Read file
      run: |
        ls -R
