name: test-deploymnet

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-test:
    uses: virtual-labs/vlabs-workflows/.github/workflows/test-ph3-lab.yml@test
    permissions:
      issues: write
    with:
      username: vikramk20
    secrets: inherit
